import { describe, expect, it } from 'vitest'
import { analyzeCode, parseGithubRepository, sampleCode, MAX_SOURCE_LENGTH } from './processor'

describe('ai code detector', () => {
  it('returns an explainable result for a code sample', () => {
    const result = analyzeCode(sampleCode())
    expect(result.valid).toBe(true)
    expect(result.score).toBeGreaterThanOrEqual(0)
    expect(result.score).toBeLessThanOrEqual(100)
    expect(result.metrics.codeLines).toBeGreaterThan(0)
    expect(result.signals.length).toBeGreaterThan(0)
    expect(result.sampleNote).toContain('当前只有')
  })

  it('rejects samples that are too short to analyze', () => {
    const result = analyzeCode('const x = 1')
    expect(result.valid).toBe(false)
    expect(result.error).toContain('20')
  })

  it('does not treat TODO markers as proof of human authorship', () => {
    const result = analyzeCode('function run() {\n  // TODO: replace this later\n  return 1\n}\n')
    expect(result.valid).toBe(true)
    expect(result.metrics.todoCount).toBe(1)
    expect(result.signals.some(signal => signal.label === '保留 TODO/FIXME')).toBe(true)
  })

  it('parses public GitHub repository URLs and shorthand', () => {
    expect(parseGithubRepository('https://github.com/vuejs/core')).toEqual({ owner: 'vuejs', repository: 'core' })
    expect(parseGithubRepository('vuejs/core.git')).toEqual({ owner: 'vuejs', repository: 'core' })
    expect(parseGithubRepository('https://gitlab.com/acme/app')).toBeNull()
  })

  it('only reports model names as unverified source markers', () => {
    const result = analyzeCode('// Generated by Claude\nexport function add(a: number, b: number) { return a + b }')
    expect(result.modelHint).toContain('Claude')
    expect(result.modelHint).toContain('不能证明')
  })
  it('rejects oversized sources before scoring', () => {
    const result = analyzeCode('x'.repeat(MAX_SOURCE_LENGTH + 1))
    expect(result.valid).toBe(false)
    expect(result.error).toContain('不能超过')
  })
})
